#############################################################################
# Makefile for building: wmit
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Oct 5 18:12:43 2010
# Project:  wmit.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile wmit.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -fstack-protector-all -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -pipe -fno-nonansi-builtins -ffor-scope -fno-exceptions -fno-rtti -fno-signed-zeros -fno-math-errno -g -fstack-protector-all -Wall -W -pedantic -Wextra -Wc++0x-compat -Wnon-virtual-dtor -Wno-long-long -Wold-style-cast -Wredundant-decls -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/QGLViewer -I/usr/X11R6/include -Imoc -Iui
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -l3ds -lm -lqglviewer-qt4 -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		ImportDialog.cpp \
		UVEditor.cpp \
		ConfigDialog.cpp \
		TransformDock.cpp \
		WZM.cpp \
		TeamColoursDock.cpp \
		Generic.cpp \
		Pie.cpp \
		QtGLView.cpp \
		Mesh.cpp \
		GLTexture.cpp \
		Util.cpp \
		QWZM.cpp \
		ExportDialog.cpp moc/moc_MainWindow.cpp \
		moc/moc_ImportDialog.cpp \
		moc/moc_UVEditor.cpp \
		moc/moc_ConfigDialog.cpp \
		moc/moc_TransformDock.cpp \
		moc/moc_TeamColoursDock.cpp \
		moc/moc_QtGLView.cpp \
		moc/moc_ExportDialog.cpp
OBJECTS       = bin/main.o \
		bin/MainWindow.o \
		bin/ImportDialog.o \
		bin/UVEditor.o \
		bin/ConfigDialog.o \
		bin/TransformDock.o \
		bin/WZM.o \
		bin/TeamColoursDock.o \
		bin/Generic.o \
		bin/Pie.o \
		bin/QtGLView.o \
		bin/Mesh.o \
		bin/GLTexture.o \
		bin/Util.o \
		bin/QWZM.o \
		bin/ExportDialog.o \
		bin/moc_MainWindow.o \
		bin/moc_ImportDialog.o \
		bin/moc_UVEditor.o \
		bin/moc_ConfigDialog.o \
		bin/moc_TransformDock.o \
		bin/moc_TeamColoursDock.o \
		bin/moc_QtGLView.o \
		bin/moc_ExportDialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		config \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		wmit.pro
QMAKE_TARGET  = wmit
DESTDIR       = 
TARGET        = wmit

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui/ui_MainWindow.h ui/ui_ImportDialog.h ui/ui_UVEditor.h ui/ui_ConfigDialog.h ui/ui_TransformDock.h ui/ui_TeamColoursDock.h ui/ui_ExportDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: wmit.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		config \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libqglviewer-qt4.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile wmit.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
config:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libqglviewer-qt4.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile wmit.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/wmit1.0.0 || $(MKDIR) bin/wmit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/wmit1.0.0/ && $(COPY_FILE) --parents MainWindow.hpp ImportDialog.hpp UVEditor.hpp ConfigDialog.hpp TransformDock.hpp Vector.hpp VectorTypes.hpp Polygon.hpp Pie.hpp WZM.hpp TeamColoursDock.hpp Generic.hpp IAnimatable.hpp QtGLView.hpp TexturedRenderable.hpp IGLRenderable.hpp IGLTextureManager.hpp GLTexture.hpp Mesh.hpp OBJ.hpp Util.hpp QWZM.hpp ExportDialog.hpp ITCMaskProvider.hpp TCMaskRenderable.hpp bin/wmit1.0.0/ && $(COPY_FILE) --parents main.cpp MainWindow.cpp ImportDialog.cpp UVEditor.cpp ConfigDialog.cpp TransformDock.cpp WZM.cpp TeamColoursDock.cpp Generic.cpp Pie.cpp QtGLView.cpp Mesh.cpp GLTexture.cpp Util.cpp QWZM.cpp ExportDialog.cpp bin/wmit1.0.0/ && $(COPY_FILE) --parents MainWindow.ui ImportDialog.ui UVEditor.ui ConfigDialog.ui TransformDock.ui TeamColoursDock.ui ExportDialog.ui bin/wmit1.0.0/ && (cd `dirname bin/wmit1.0.0` && $(TAR) wmit1.0.0.tar wmit1.0.0 && $(COMPRESS) wmit1.0.0.tar) && $(MOVE) `dirname bin/wmit1.0.0`/wmit1.0.0.tar.gz . && $(DEL_FILE) -r bin/wmit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_MainWindow.cpp moc/moc_ImportDialog.cpp moc/moc_UVEditor.cpp moc/moc_ConfigDialog.cpp moc/moc_TransformDock.cpp moc/moc_TeamColoursDock.cpp moc/moc_QtGLView.cpp moc/moc_ExportDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_MainWindow.cpp moc/moc_ImportDialog.cpp moc/moc_UVEditor.cpp moc/moc_ConfigDialog.cpp moc/moc_TransformDock.cpp moc/moc_TeamColoursDock.cpp moc/moc_QtGLView.cpp moc/moc_ExportDialog.cpp
moc/moc_MainWindow.cpp: QWZM.hpp \
		WZM.hpp \
		Mesh.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		OBJ.hpp \
		IGLRenderable.hpp \
		TexturedRenderable.hpp \
		GLTexture.hpp \
		IGLTextureManager.hpp \
		TCMaskRenderable.hpp \
		ITCMaskProvider.hpp \
		IAnimatable.hpp \
		MainWindow.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.hpp -o moc/moc_MainWindow.cpp

moc/moc_ImportDialog.cpp: ImportDialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ImportDialog.hpp -o moc/moc_ImportDialog.cpp

moc/moc_UVEditor.cpp: UVEditor.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) UVEditor.hpp -o moc/moc_UVEditor.cpp

moc/moc_ConfigDialog.cpp: ConfigDialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ConfigDialog.hpp -o moc/moc_ConfigDialog.cpp

moc/moc_TransformDock.cpp: TransformDock.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TransformDock.hpp -o moc/moc_TransformDock.cpp

moc/moc_TeamColoursDock.cpp: TeamColoursDock.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TeamColoursDock.hpp -o moc/moc_TeamColoursDock.cpp

moc/moc_QtGLView.cpp: GLTexture.hpp \
		IGLTextureManager.hpp \
		ITCMaskProvider.hpp \
		QtGLView.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) QtGLView.hpp -o moc/moc_QtGLView.cpp

moc/moc_ExportDialog.cpp: ExportDialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ExportDialog.hpp -o moc/moc_ExportDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_MainWindow.h ui/ui_ImportDialog.h ui/ui_UVEditor.h ui/ui_ConfigDialog.h ui/ui_TransformDock.h ui/ui_TeamColoursDock.h ui/ui_ExportDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_MainWindow.h ui/ui_ImportDialog.h ui/ui_UVEditor.h ui/ui_ConfigDialog.h ui/ui_TransformDock.h ui/ui_TeamColoursDock.h ui/ui_ExportDialog.h
ui/ui_MainWindow.h: MainWindow.ui \
		QtGLView.hpp \
		GLTexture.hpp \
		IGLTextureManager.hpp \
		ITCMaskProvider.hpp
	/usr/bin/uic-qt4 MainWindow.ui -o ui/ui_MainWindow.h

ui/ui_ImportDialog.h: ImportDialog.ui
	/usr/bin/uic-qt4 ImportDialog.ui -o ui/ui_ImportDialog.h

ui/ui_UVEditor.h: UVEditor.ui
	/usr/bin/uic-qt4 UVEditor.ui -o ui/ui_UVEditor.h

ui/ui_ConfigDialog.h: ConfigDialog.ui
	/usr/bin/uic-qt4 ConfigDialog.ui -o ui/ui_ConfigDialog.h

ui/ui_TransformDock.h: TransformDock.ui
	/usr/bin/uic-qt4 TransformDock.ui -o ui/ui_TransformDock.h

ui/ui_TeamColoursDock.h: TeamColoursDock.ui
	/usr/bin/uic-qt4 TeamColoursDock.ui -o ui/ui_TeamColoursDock.h

ui/ui_ExportDialog.h: ExportDialog.ui
	/usr/bin/uic-qt4 ExportDialog.ui -o ui/ui_ExportDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

bin/main.o: main.cpp MainWindow.hpp \
		QWZM.hpp \
		WZM.hpp \
		Mesh.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		OBJ.hpp \
		IGLRenderable.hpp \
		TexturedRenderable.hpp \
		GLTexture.hpp \
		IGLTextureManager.hpp \
		TCMaskRenderable.hpp \
		ITCMaskProvider.hpp \
		IAnimatable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/main.o main.cpp

bin/MainWindow.o: MainWindow.cpp MainWindow.hpp \
		QWZM.hpp \
		WZM.hpp \
		Mesh.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		OBJ.hpp \
		IGLRenderable.hpp \
		TexturedRenderable.hpp \
		GLTexture.hpp \
		IGLTextureManager.hpp \
		TCMaskRenderable.hpp \
		ITCMaskProvider.hpp \
		IAnimatable.hpp \
		ui/ui_MainWindow.h \
		QtGLView.hpp \
		ConfigDialog.hpp \
		TransformDock.hpp \
		ImportDialog.hpp \
		ExportDialog.hpp \
		UVEditor.hpp \
		Pie.hpp \
		Pie_t.cpp \
		Generic.hpp \
		Util.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/MainWindow.o MainWindow.cpp

bin/ImportDialog.o: ImportDialog.cpp ImportDialog.hpp \
		ui/ui_ImportDialog.h \
		Util.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/ImportDialog.o ImportDialog.cpp

bin/UVEditor.o: UVEditor.cpp UVEditor.hpp \
		ui/ui_UVEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/UVEditor.o UVEditor.cpp

bin/ConfigDialog.o: ConfigDialog.cpp ConfigDialog.hpp \
		ui/ui_ConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/ConfigDialog.o ConfigDialog.cpp

bin/TransformDock.o: TransformDock.cpp TransformDock.hpp \
		ui/ui_TransformDock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/TransformDock.o TransformDock.cpp

bin/WZM.o: WZM.cpp WZM.hpp \
		Mesh.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		OBJ.hpp \
		Generic.hpp \
		Util.hpp \
		Pie.hpp \
		Pie_t.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/WZM.o WZM.cpp

bin/TeamColoursDock.o: TeamColoursDock.cpp TeamColoursDock.hpp \
		ui/ui_TeamColoursDock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/TeamColoursDock.o TeamColoursDock.cpp

bin/Generic.o: Generic.cpp Generic.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Generic.o Generic.cpp

bin/Pie.o: Pie.cpp Pie.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		WZM.hpp \
		Mesh.hpp \
		OBJ.hpp \
		Pie_t.cpp \
		Generic.hpp \
		Util.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Pie.o Pie.cpp

bin/QtGLView.o: QtGLView.cpp QtGLView.hpp \
		GLTexture.hpp \
		IGLTextureManager.hpp \
		ITCMaskProvider.hpp \
		TexturedRenderable.hpp \
		IGLRenderable.hpp \
		TCMaskRenderable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/QtGLView.o QtGLView.cpp

bin/Mesh.o: Mesh.cpp Mesh.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		OBJ.hpp \
		Generic.hpp \
		Util.hpp \
		Pie.hpp \
		WZM.hpp \
		Pie_t.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Mesh.o Mesh.cpp

bin/GLTexture.o: GLTexture.cpp GLTexture.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/GLTexture.o GLTexture.cpp

bin/Util.o: Util.cpp Util.hpp \
		Pie.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		WZM.hpp \
		Mesh.hpp \
		OBJ.hpp \
		Pie_t.cpp \
		Generic.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Util.o Util.cpp

bin/QWZM.o: QWZM.cpp QWZM.hpp \
		WZM.hpp \
		Mesh.hpp \
		VectorTypes.hpp \
		Vector.hpp \
		Polygon.hpp \
		Polygon_t.cpp \
		OBJ.hpp \
		IGLRenderable.hpp \
		TexturedRenderable.hpp \
		GLTexture.hpp \
		IGLTextureManager.hpp \
		TCMaskRenderable.hpp \
		ITCMaskProvider.hpp \
		IAnimatable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/QWZM.o QWZM.cpp

bin/ExportDialog.o: ExportDialog.cpp ExportDialog.hpp \
		ui/ui_ExportDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/ExportDialog.o ExportDialog.cpp

bin/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_MainWindow.o moc/moc_MainWindow.cpp

bin/moc_ImportDialog.o: moc/moc_ImportDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_ImportDialog.o moc/moc_ImportDialog.cpp

bin/moc_UVEditor.o: moc/moc_UVEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_UVEditor.o moc/moc_UVEditor.cpp

bin/moc_ConfigDialog.o: moc/moc_ConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_ConfigDialog.o moc/moc_ConfigDialog.cpp

bin/moc_TransformDock.o: moc/moc_TransformDock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_TransformDock.o moc/moc_TransformDock.cpp

bin/moc_TeamColoursDock.o: moc/moc_TeamColoursDock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_TeamColoursDock.o moc/moc_TeamColoursDock.cpp

bin/moc_QtGLView.o: moc/moc_QtGLView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_QtGLView.o moc/moc_QtGLView.cpp

bin/moc_ExportDialog.o: moc/moc_ExportDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_ExportDialog.o moc/moc_ExportDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

