#!/bin/bash -e
# QT-CI Project
# License: Apache-2.0
# https://github.com/benlau/qtci
#
# Reference:
#   https://github.com/musescore/MuseScore/blob/master/build/travis/job_macos/install.sh
#
# Modified: to support finding extract-qt-installer in the same directory as this script

QT_VERSION=${1:-5.12.0}
QT_TARGET_CATALOG=${2:-$PWD}
QT_CI_DOWNLOADER=${QT_CI_DOWNLOADER:-"wget -c -N"}

get_script_dir () {
	# See: https://stackoverflow.com/a/246128
	SOURCE="${BASH_SOURCE[0]}"
	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
	  SOURCE="$(readlink "$SOURCE")"
	  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done
	DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
	echo "$DIR"
}
SCRIPT_DIR="$(get_script_dir)"

if [ "$(uname)" = "Darwin" ]; then
  DOWNLOAD_URL=https://download.qt.io/archive/qt/$(echo ${QT_VERSION} | cut -d "." -f -2)/${QT_VERSION}/qt-opensource-mac-x64-${QT_VERSION}.dmg
  COMPILER=clang_64
elif [ "$(uname)" = "Linux" ]; then
  DOWNLOAD_URL=https://download.qt.io/archive/qt/$(echo ${QT_VERSION} | cut -d "." -f -2)/${QT_VERSION}/qt-opensource-linux-x64-${QT_VERSION}.run
  COMPILER=gcc_64
else
  echo "Unsupported system." >&2
  exit 1
fi
INSTALLER=$(basename $DOWNLOAD_URL)
ENVFILE=${QT_TARGET_CATALOG}/qt-${QT_VERSION}.env

echo Downloading Qt
${QT_CI_DOWNLOADER} ${DOWNLOAD_URL} || exit 1

echo Installing Qt
if [ "$(uname)" = "Darwin" ]; then
  INSTALLER_NAME=${INSTALLER%.*}
  APPFILE=/Volumes/${INSTALLER_NAME}/${INSTALLER_NAME}.app/Contents/MacOS/${INSTALLER_NAME}
  hdiutil attach ${PWD}/${INSTALLER}
  ${SCRIPT_DIR}/extract-qt-installer $APPFILE ${QT_TARGET_CATALOG}/Qt
  hdiutil detach /Volumes/${INSTALLER_NAME}
elif [ "$(uname)" = "Linux" ]; then
  ${SCRIPT_DIR}/extract-qt-installer ${PWD}/${INSTALLER} ${QT_TARGET_CATALOG}/Qt
fi

echo Create ${ENVFILE}
if [ -d "${QT_TARGET_CATALOG}/Qt/${QT_VERSION}/${COMPILER}/bin" ]; then
  echo "export PATH=${QT_TARGET_CATALOG}/Qt/${QT_VERSION}/${COMPILER}/bin:$PATH" > ${ENVFILE}
elif [ -d "${QT_TARGET_CATALOG}/Qt/$(echo ${QT_VERSION} | cut -d "." -f -2)/${COMPILER}/bin" ]; then
  # some packages use an abbreviated version x.y in the path instead of x.y.z
  echo "export PATH=${QT_TARGET_CATALOG}/Qt/$(echo ${QT_VERSION} | cut -d "." -f -2)/${COMPILER}/bin:$PATH" > ${ENVFILE}
fi

